import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SessionAuthProvider from "@/context/SessionAuthProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-gray-200 pb-[110px] relative min-h-screen dark:bg-slate-900 ">
      <SessionAuthProvider>
        <Navbar />
        {children}
        <Footer />
        </SessionAuthProvider>
        </body>
    </html>
  );
}
